controller_manager:
  ros__parameters:
    update_rate: 30
    image_sensor_broadcaster:
      type: "image_sensor_broadcaster/ImageSensorBroadcaster"

    imu_sensor_broadcaster:
      type: "imu_sensor_broadcaster/IMUSensorBroadcaster"

image_sensor_broadcaster:
  ros__parameters:
    sensor_name: "mgs1600gy_magnet_link"
    frame_id: "base_link"
    encoding: "rgb8"
    height: 1
    width: 16

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "mgs1600gy_link"
    frame_id: "base_link"
